builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
# universal_binaries:
# - replace: true